# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyHistoryStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generations', models.IntegerField(blank=True, default=0)),
                ('indexed', models.IntegerField(blank=True, default=0)),
                ('memories', models.IntegerField(blank=True, default=0)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family_history.FamilyHistoryStats')),
            ],
        ),
    ]
