# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyhistorystats',
            name='names',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
